@startuml Mention Plataform
set separator none
title Mention Plataform - API Application - Components

' top to bottom direction
' left to right direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Mention Plataform")
Boundary(mention_zone, "Mention Zone") {
    Person(Operator, "Operator", "Operatro of the plataform", $tags="")
    Person(Admin, "Admin", "Admin of the plataform", $tags="")
    System(Frontend, "Web Frontend", "Allows users signin, signup, view information and make interactiron with systems resources as orders, profile, user managment, make interaction with other users, etc.", $tags="")
    System(Backend, "Backend API", "Provide a network interface to access the plataform resouces as subscription, order production, user management, message comunication distribuition, reports, etc.", $tags="")
}

Person(User, "User", "Customer of the plataform", $tags="")
System_Ext(Cloud, "Cloud", "Cloud services", $tags="")
System_Ext(ERP, "ERP", "Enterprise Resource Planning", $tags="")
System_Ext(CRM, "CRM", "Customer Relationship Management", $tags="")

Rel_D(User, Frontend, "View your orders, subscription data, etc and make orders")
Rel_D(Frontend, Backend, "Make requests for the plataform services")
Rel_L(Operator, Frontend, "View and manage orders, subscription data, etc")
Rel_R(Admin, Frontend, "View and manage orders, subscription data, etc")
Rel_L(Admin, Backend, "Interact with cli console to manage plataform resources")
Rel_U(Backend, ERP, "Make requests for billing services")
Rel_L(Backend, CRM, "Make requests for CRM services")
Rel_D(Backend, Cloud, "Make requests for cloud services")

@enduml